// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDda7wdb0hPDe-3MFIdit11Q4QhqbS8_XA',
    appId: '1:384094956935:web:f68b10bcb9dcbb77607722',
    messagingSenderId: '384094956935',
    projectId: 'recherchelivraisonmedicament',
    authDomain: 'recherchelivraisonmedicament.firebaseapp.com',
    storageBucket: 'recherchelivraisonmedicament.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfTdi-cWiDR61Hn7t5hfBZwc-C4E8TQPU',
    appId: '1:384094956935:android:b5f237135f8be1e6607722',
    messagingSenderId: '384094956935',
    projectId: 'recherchelivraisonmedicament',
    storageBucket: 'recherchelivraisonmedicament.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbx8FMH8kGEt4l9on4BR3ph30dDaOpw5Y',
    appId: '1:384094956935:ios:89f22cfd779f9882607722',
    messagingSenderId: '384094956935',
    projectId: 'recherchelivraisonmedicament',
    storageBucket: 'recherchelivraisonmedicament.firebasestorage.app',
    iosBundleId: 'com.siso.recherchelivraisonmedicament',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbx8FMH8kGEt4l9on4BR3ph30dDaOpw5Y',
    appId: '1:384094956935:ios:89f22cfd779f9882607722',
    messagingSenderId: '384094956935',
    projectId: 'recherchelivraisonmedicament',
    storageBucket: 'recherchelivraisonmedicament.firebasestorage.app',
    iosBundleId: 'com.siso.recherchelivraisonmedicament',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDda7wdb0hPDe-3MFIdit11Q4QhqbS8_XA',
    appId: '1:384094956935:web:ec8e1a3f6cbd9a56607722',
    messagingSenderId: '384094956935',
    projectId: 'recherchelivraisonmedicament',
    authDomain: 'recherchelivraisonmedicament.firebaseapp.com',
    storageBucket: 'recherchelivraisonmedicament.firebasestorage.app',
  );

}