// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcZQJ-sLekxNu1H4v5ajdWT4iJuWz-ozw',
    appId: '1:281188786362:web:06db584463fffb0cd6e283',
    messagingSenderId: '281188786362',
    projectId: 'recherchelivraisonmedica-feca8',
    authDomain: 'recherchelivraisonmedica-feca8.firebaseapp.com',
    storageBucket: 'recherchelivraisonmedica-feca8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuCzqZ9UCykd9oKLCspVnbvyQMSMP0ZVc',
    appId: '1:281188786362:android:9ce541fffeb5fb84d6e283',
    messagingSenderId: '281188786362',
    projectId: 'recherchelivraisonmedica-feca8',
    storageBucket: 'recherchelivraisonmedica-feca8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7wp0fKtNqCrgjjQl8b8_Y8ugf3z1vah8',
    appId: '1:281188786362:ios:4c699758e86cb36ad6e283',
    messagingSenderId: '281188786362',
    projectId: 'recherchelivraisonmedica-feca8',
    storageBucket: 'recherchelivraisonmedica-feca8.firebasestorage.app',
    iosBundleId: 'com.siso.recherchelivraisonmedicament',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7wp0fKtNqCrgjjQl8b8_Y8ugf3z1vah8',
    appId: '1:281188786362:ios:4c699758e86cb36ad6e283',
    messagingSenderId: '281188786362',
    projectId: 'recherchelivraisonmedica-feca8',
    storageBucket: 'recherchelivraisonmedica-feca8.firebasestorage.app',
    iosBundleId: 'com.siso.recherchelivraisonmedicament',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcZQJ-sLekxNu1H4v5ajdWT4iJuWz-ozw',
    appId: '1:281188786362:web:018189bfe84041f5d6e283',
    messagingSenderId: '281188786362',
    projectId: 'recherchelivraisonmedica-feca8',
    authDomain: 'recherchelivraisonmedica-feca8.firebaseapp.com',
    storageBucket: 'recherchelivraisonmedica-feca8.firebasestorage.app',
  );

}